import {
  pgTable,
  serial,
  text,
  integer,
  doublePrecision,
  timestamp,
  jsonb,
  index,
} from 'drizzle-orm/pg-core';

export const spans = pgTable(
  'spans',
  {
    id: serial('id').primaryKey(),
    traceId: text('trace_id').notNull(),
    spanId: text('span_id').notNull(),
    parentSpanId: text('parent_span_id'),
    name: text('name').notNull(),
    kind: integer('kind').notNull().default(0),
    startTimeUnixNano: text('start_time_unix_nano').notNull(),
    endTimeUnixNano: text('end_time_unix_nano').notNull(),
    durationMs: doublePrecision('duration_ms').notNull(),
    statusCode: integer('status_code').notNull().default(0),
    statusMessage: text('status_message').default(''),
    serviceName: text('service_name').notNull().default('unknown'),
    resourceAttributes: jsonb('resource_attributes').default({}),
    spanAttributes: jsonb('span_attributes').default({}),
    events: jsonb('events').default([]),
    links: jsonb('links').default([]),
    scopeName: text('scope_name').default(''),
    scopeVersion: text('scope_version').default(''),
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
  (table) => [
    index('spans_trace_id_idx').on(table.traceId),
    index('spans_service_name_idx').on(table.serviceName),
    index('spans_start_time_idx').on(table.startTimeUnixNano),
    index('spans_status_code_idx').on(table.statusCode),
  ],
);

export const metricDataPoints = pgTable(
  'metric_data_points',
  {
    id: serial('id').primaryKey(),
    name: text('name').notNull(),
    description: text('description').default(''),
    unit: text('unit').default(''),
    type: text('type').notNull(),
    value: doublePrecision('value'),
    count: integer('count'),
    sum: doublePrecision('sum'),
    buckets: jsonb('buckets'),
    quantiles: jsonb('quantiles'),
    timeUnixNano: text('time_unix_nano').notNull(),
    startTimeUnixNano: text('start_time_unix_nano').default(''),
    serviceName: text('service_name').notNull().default('unknown'),
    resourceAttributes: jsonb('resource_attributes').default({}),
    attributes: jsonb('attributes').default({}),
    scopeName: text('scope_name').default(''),
    scopeVersion: text('scope_version').default(''),
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
  (table) => [
    index('metrics_name_idx').on(table.name),
    index('metrics_service_name_idx').on(table.serviceName),
    index('metrics_time_idx').on(table.timeUnixNano),
  ],
);

export const logs = pgTable(
  'logs',
  {
    id: serial('id').primaryKey(),
    timeUnixNano: text('time_unix_nano').notNull(),
    observedTimeUnixNano: text('observed_time_unix_nano').default(''),
    severityNumber: integer('severity_number').notNull().default(0),
    severityText: text('severity_text').default(''),
    body: text('body').default(''),
    traceId: text('trace_id'),
    spanId: text('span_id'),
    serviceName: text('service_name').notNull().default('unknown'),
    resourceAttributes: jsonb('resource_attributes').default({}),
    attributes: jsonb('attributes').default({}),
    scopeName: text('scope_name').default(''),
    scopeVersion: text('scope_version').default(''),
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
  (table) => [
    index('logs_trace_id_idx').on(table.traceId),
    index('logs_service_name_idx').on(table.serviceName),
    index('logs_severity_idx').on(table.severityNumber),
    index('logs_time_idx').on(table.timeUnixNano),
  ],
);
